export interface ApplicationForm {
    daApplicationTypeId: number,
    name: string,
    dob: string,
    nrcNo: string,
    fatherName: string,
    nationality: number,
    nationalityOther: string,
    gender: number,
    maritalStatus: number,
    currentAddress: string,
    permanentAddress: string,
    typeOfResidence: number,
    typeOfResidenceOther: string,
    livingWith: number,
    livingWithOther: string,
    yearOfStayYear: number,
    yearOfStayMonth: number,
    mobileNo: string,
    residentTelNo: string,
    otherPhoneNo: string,
    email: string,
    customerId: number,
    daLoanTypeId: number,
    financeAmount: number,
    financeTerm: number,
    daProductTypeId: number,
    productDescription: string,
    channelType: number,
    applicationInfoAttachmentDtoList: any,
    applicantCompanyInfoDto: any,
    emergencyContactInfoDto: any,
    guarantorInfoDto: any

}