export class Register {
    daApplicationTypeId: any;
    name: any;
    dob: any;
    nrcNo: any;
    fatherName: any;
    nationality: any;
    nationalityOther: any;
    gender: any;
    maritalStatus: any;
    currentAddress: any;
    permanentAddress: any;
    typeOfResidence: any;
    typeOfResidenceOther: any;
    livingWith: any;
    livingWithOther: any;
    yearOfStayYear: any;
    yearOfStayMonth: any;
    mobileNo: any;
    residentTelNo: any;
    otherPhoneNo: any;
    email: any;
    customerId: any;
    daLoanTypeId: any;
    financeAmount:any;
    financeTerm: any;
    daProductTypeId: any;
    productDescription: any;
    channelType: any;
    applicationInfoAttachmentDtoList: any;
    applicantCompanyInfoDto: any;
    emergencyContactInfoDto: any;
    guarantorInfoDto: any;
}
